Algoritmo "EXERCICIO DESAFIO DO GPT - "
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 02/10/2023
Var
// Seção de Declarações das variáveis 
  cal, contador: inteiro
  M, N: real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
         escreva ("Quantos calculos deseja realizar? ")
         leia (Cal)
         N <- 0
         contador <- 1
         enquanto (contador <= cal) faca
                  escreva ("Insira o ", contador,"o número:")
                  leia (N)
                  contador <- contador + 1
                  M <- N  / Cal
         fimenquanto
         escreva ("A média dos números inseridos foi: ", M:5:2)
Fimalgoritmo